version: 2.1
orbs:
    node: circleci/node@1.1.6
jobs:
    build-and-deploy:
        docker:
            - image: amaysim/serverless
              auth:
                username: munawersheikh
                password: $DOCKERHUB_PASSWORD
        steps:
            - checkout
            - restore_cache:
                keys:
                - v1-deps-{{ checksum "package.json" }}
            - save_cache:
                key: v1-deps-{{ checksum "package.json" }}
                paths:
                - node_modules   
                  /usr/local/lib/node_modules
            - run: npm -v

workflows:
    build-and-deploy:
        jobs:
            - build-and-deploy:
                  filters:
                      branches:
                          only:
                              - main
