version: 2.1
orbs:
    node: circleci/node@1.1.6
jobs:
    build-and-deploy:
        docker:
            - image: circleci/node:16.8.0
        steps:
            - checkout
            - restore_cache:
                keys:
                - v1-deps-{{ checksum "package.json" }}
            - run: sudo npm i -g jest
            - save_cache:
                key: v1-deps-{{ checksum "package.json" }}
                paths:
                - /usr/local/lib/node_modules/jest         
            - run: npm run test
workflows:
    build-and-deploy:
        jobs:
            - build-and-deploy:
                  filters:
                      branches:
                          only:
                              - main
