version: 2.1
orbs:
    node: circleci/node@1.1.6
jobs:
    build-and-deploy:
        docker:
            - image: circleci/node:16.8.0
        steps:
            - checkout
            - run: sudo npm i -g jest
            - run: ls
            - run: cd ~
            - run: cd /home/
            - run: ls
workflows:
    build-and-deploy:
        jobs:
            - build-and-deploy:
                  filters:
                      branches:
                          only:
                              - main
